name: CI / Byte-Compile

on:
  push:
    tags:
      - "v*"
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '28.2'
          - '29.4'
          - '30.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Install dependencies
        run: |
          emacs -Q --batch \
            --eval "(require 'package)" \
            --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" \
            --eval "(package-initialize)" \
            --eval "(package-refresh-contents)" \
            --eval "(package-install 'nerd-icons)"

      - name: Byte-compile bufferline.el modules
        run: |
          emacs -Q --batch \
            --eval "(require 'package)" \
            --eval "(package-initialize)" \
            -L . \
            -f batch-byte-compile *.el
